#!/bin/bash

libtoolize --automake --force --copy \
&& aclocal \
&& autoheader \
&& automake --gnu --add-missing --copy \
&& autoconf

for dir in prvparser pcfparser
do
	cd $dir && ./bootstrap && cd ..
done

if test `basename ${0}` = "bootstrap-and-dist" ; then
        ./configure 
        make dist-bzip2
fi
